[project]
name = "homelab"
version = "1.1.0"
description = ""
authors = [{ name = "Ezequiel Valencia" }]
requires-python = ">=3.11,<4"
readme = "README.md"
dependencies = [
    "ansible>=11.0.0,<12",
    "pyyaml>=6.0.1,<7",
    "ansible-core>=2.18.0,<3",
    "ansible-lint>=25",
]


