$ANSIBLE_VAULT;1.1;AES256
38326538326664383634646364373966353461386563333633333932336464613863616665386332
3136346636356538313262646262636464356262616133300a393964353065393663326630643031
36316163336634613165343964306430326330346639656534383439373039633162626638356166
3235373434356230320a633739396665656562323364356163643265633434343133636566663335
34363966633433636338316337613539346664313431356339383766653636613761373733373831
3965623938643165373432663033383532353337343830386338
