---
- name: Create Traefik Resource
  vars:
    docker_template_files: []
    source_compose_file: dashy.compose.yml
    remote_compose_file: dashy.compose
    compose_project_name: dashy
  ansible.builtin.include_tasks: ../tasks/docker-compose-up.yml
