---
- name: Update grub
  become: true
  ansible.builtin.command: update-grub
  changed_when: true

- name: Update initramfs
  become: true
  ansible.builtin.command: update-initramfs -u -k all
  changed_when: true
