
services:
  traefik:
    image: traefik:3.6.1
    container_name: traefik
    restart: unless-stopped
    user: {{ infra_install_traefik_local_user }}
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    environment:
      - CF_DNS_API_TOKEN={{ cloudflare_token }}
      - CF_ZONE_API_TOKEN={{ cloudflare_token }}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - {{ defualt_relative_docker_data_path }}/traefik/traefik.yml:/traefik.yml:ro
      - {{ defualt_relative_docker_data_path }}/traefik/acme.json:/acme.json
      - {{ defualt_relative_docker_data_path }}/traefik/config.yml:/config.yml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik-dashboard.homelab.ezequielvalencia.com`)"
      
      # password has to be a hash of actual passwd
      # - "traefik.http.middlewares.traefik-auth.basicauth.users={{ traefik_user }}:{{ traefik_password }}"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik-dashboard.homelab.ezequielvalencia.com`)"
      - "traefik.http.routers.traefik-secure.middlewares=authelia"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflareResolver"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=homelab.ezequielvalencia.com"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.homelab.ezequielvalencia.com"
      - "traefik.http.routers.traefik-secure.service=api@internal"
    
  pihole:
      image: pihole/pihole
      restart: always
      container_name: pihole
      pull_policy: always 
      networks:
        - proxy
      ports:
          - "53:53/tcp"
          - "53:53/udp"
      environment:
          - TZ={{ time_zone }}
          - WEBTHEME=default-dark
          - PIHOLE_DNS_=9.9.9.9;1.1.1.1
          - DNSSEC="true"
      volumes:
          - "{{ defualt_relative_docker_data_path }}/pihole:/etc/pihole"
          - "{{ defualt_relative_docker_data_path }}/pihole-dnsmasq.d:/etc/dnsmasq.d"
  
  authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - {{ infra_install_authelia_volume_folder }}:/config
    networks:
      proxy:
        aliases:
          - authelia
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.authelia.rule=Host(`auth.homelab.ezequielvalencia.com`)'
      - 'traefik.http.routers.authelia.entrypoints=https'
      - 'traefik.http.routers.authelia.tls=true'
      - 'traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.homelab.ezequielvalencia.com' # Docker automatic resolve of authelia name to internal IP
      - 'traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'
    # ports:
    #   - 127.0.0.1:9091:9091
    restart: unless-stopped
    environment:
      - TZ={{ time_zone }}

networks:
  proxy:


# https://www.baeldung.com/ops/docker-assign-static-ip-container
# https://stackoverflow.com/questions/47187879/docker-compose-use-other-container-as-dns
# https://forums.docker.com/t/using-container-as-dns-server-for-another-compose-app/144166
