---
- name: Init VM Nodes for K8
  hosts: node
  gather_facts: false
  vars:
    other_port: true
    alt_ssh_port: 5320
    is_qemu_guest: true
    longhorn_node: true
    setup_packages:
      - vim
      - nfs-common
      - open-iscsi
      - cryptsetup
      - htop

  pre_tasks:
    - name: Get Facts and Switch Python Env
      ansible.builtin.include_tasks: ../../tasks/change-and-gather.yml

  roles:
    - debian-system-startup

- name: Init Media Node for K8
  hosts: media
  gather_facts: false
  vars:
    other_port: true
    alt_ssh_port: 5320

  pre_tasks:
    - name: Get Facts and Switch Python Env
      ansible.builtin.include_tasks: ../../tasks/change-and-gather.yml

  roles:
    - media_install
