infra_install_traefik_files:
  - traefik.yml
  - config.yml


infra_install_traefik_local_user: root


infra_install_authelia_volume_folder: '{{ defualt_relative_docker_data_path }}/authelia'

# authelia_internal_alias: authelia


# etc_resolv_path: "/etc/resolv.conf"
# etc_resolv_src: "/run/systemd/resolve/resolv.conf"

# netplan_dir: "/etc/netplan"
