
services:
  dashy:
    image: lissy93/dashy:latest
    restart: always
    container_name: dashy
    dns: 10.0.0.6
    ports:
      - 8080:8080
    volumes:
    - "{{ defualt_relative_docker_data_path }}/dashy:/app/user-data"



# https://www.baeldung.com/ops/docker-assign-static-ip-container
# https://stackoverflow.com/questions/47187879/docker-compose-use-other-container-as-dns
# https://forums.docker.com/t/using-container-as-dns-server-for-another-compose-app/144166
