---
- name: Init Proxmox Machines
  hosts: proxmox_servers
  vars:
    other_port: false

  roles:
    - proxmox-init

- name: PCIE Passthrough
  hosts: zpc2
  vars:
    pve_cpu_vendor: "intel"
    # GTX Quadro T1000 and its audio device directly to vfio
    pve_vfio_pci_ids: "10de:1fb9,10de:10fa"
    pve_acs_override: false
  roles:
    - pcie-passthrough
