$ANSIBLE_VAULT;1.1;AES256
61313434643935323330303964626561643435663734656163383839336333623638313333343137
3730343037393663303332646238613362636539393339380a386432353762316165323466613164
37663231376362626337656336633832313966623930306131316537313665663633623265333532
3761396665656437310a373133356363643437376566643761646134386637646561373333303130
66373439333563313639306133373531343064313033313963616136333337376632653330666364
65343166333566646332623861326637623536626566326138323362363030656364666661396130
32623934373238336237653834313538613231393633336261343663653862666631353732386235
39373437333865626564363564666564363962663863656235616238373033373962613262343239
65353061353439303535623061313939636233393733626237616630613965633035633531643666
35376234393439316165646637653134333965313337333661666166643661653833333165386266
303832643665366530353061653134323039
