---
- name: Apply Debian VM Policy
  ansible.builtin.import_playbook: debian_policy.yml

- name: Infrastructure
  ansible.builtin.import_playbook: initialize/all_infrastructure.yml

- name: K8 Nodes
  ansible.builtin.import_playbook: initialize/all_k8.yml

- name: Public Services
  ansible.builtin.import_playbook: initialize/public_services.yml
